# Generated by Django 4.2.5 on 2023-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Crystal Box', 'Crystal Box'), ('Crystal Bar', 'Crystal Bar'), ('2800 puff', '2800 puff')], max_length=20, null=True),
        ),
    ]
