# Generated by Django 4.2.5 on 2023-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('0% Nic 600 Puff', '0% Nic 600 Puff'), ('2% Nic 600 Puff', '2% Nic 600 Puff'), ('5% Nic 600 Puff', '5% Nic 600 Puff'), ('0% Nic 2800 Puff', '0% Nic 2800 Puff'), ('2% Nic 2800 Puff', '2% Nic 2800 Puff'), ('5% Nic 2800 Puff', '5% Nic 2800 Puff'), ('0% Nic 7000 Puff', '0% Nic 7000 Puff'), ('2% Nic 7000 Puff', '2% Nic 7000 Puff'), ('5% Nic 7000 Puff', '5% Nic 7000 Puff'), ('0% Nic 8000 Puff', '0% Nic 8000 Puff'), ('2% Nic 8000 Puff', '2% Nic 8000 Puff'), ('5% Nic 8000 Puff', '5% Nic 8000 Puff')], max_length=20, null=True),
        ),
    ]
